# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/CNN_design/CNN_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CNN_design || ORIG_REF_NAME==CNN_design} -quiet] -quiet

# IP: bd/CNN_design/ip/CNN_design_processing_system7_0_0/CNN_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CNN_design_processing_system7_0_0 || ORIG_REF_NAME==CNN_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/CNN_design/ip/CNN_design_axi_lite_0_0/CNN_design_axi_lite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CNN_design_axi_lite_0_0 || ORIG_REF_NAME==CNN_design_axi_lite_0_0} -quiet] -quiet

# IP: bd/CNN_design/ip/CNN_design_xbar_0/CNN_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CNN_design_xbar_0 || ORIG_REF_NAME==CNN_design_xbar_0} -quiet] -quiet

# IP: bd/CNN_design/ip/CNN_design_ps7_0_axi_periph_0/CNN_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CNN_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==CNN_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/CNN_design/ip/CNN_design_rst_ps7_0_50M_0/CNN_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CNN_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==CNN_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/CNN_design/ip/CNN_design_auto_pc_0/CNN_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CNN_design_auto_pc_0 || ORIG_REF_NAME==CNN_design_auto_pc_0} -quiet] -quiet

# XDC: bd/CNN_design/ip/CNN_design_processing_system7_0_0/CNN_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CNN_design_processing_system7_0_0 || ORIG_REF_NAME==CNN_design_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/CNN_design/ip/CNN_design_rst_ps7_0_50M_0/CNN_design_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CNN_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==CNN_design_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CNN_design/ip/CNN_design_rst_ps7_0_50M_0/CNN_design_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CNN_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==CNN_design_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CNN_design/ip/CNN_design_auto_pc_0/CNN_design_auto_pc_0_ooc.xdc

# XDC: bd/CNN_design/CNN_design_ooc.xdc
