# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/CNN_top_module/CNN_top_module.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CNN_top_module || ORIG_REF_NAME==CNN_top_module} -quiet] -quiet

# IP: bd/CNN_top_module/ip/CNN_top_module_processing_system7_0_0/CNN_top_module_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CNN_top_module_processing_system7_0_0 || ORIG_REF_NAME==CNN_top_module_processing_system7_0_0} -quiet] -quiet

# IP: bd/CNN_top_module/ip/CNN_top_module_axi_cnn_0_0/CNN_top_module_axi_cnn_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CNN_top_module_axi_cnn_0_0 || ORIG_REF_NAME==CNN_top_module_axi_cnn_0_0} -quiet] -quiet

# IP: bd/CNN_top_module/ip/CNN_top_module_ps7_0_axi_periph_0/CNN_top_module_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CNN_top_module_ps7_0_axi_periph_0 || ORIG_REF_NAME==CNN_top_module_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/CNN_top_module/ip/CNN_top_module_rst_ps7_0_50M_0/CNN_top_module_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CNN_top_module_rst_ps7_0_50M_0 || ORIG_REF_NAME==CNN_top_module_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/CNN_top_module/ip/CNN_top_module_auto_pc_0/CNN_top_module_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CNN_top_module_auto_pc_0 || ORIG_REF_NAME==CNN_top_module_auto_pc_0} -quiet] -quiet

# XDC: bd/CNN_top_module/ip/CNN_top_module_processing_system7_0_0/CNN_top_module_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CNN_top_module_processing_system7_0_0 || ORIG_REF_NAME==CNN_top_module_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/CNN_top_module/ip/CNN_top_module_rst_ps7_0_50M_0/CNN_top_module_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CNN_top_module_rst_ps7_0_50M_0 || ORIG_REF_NAME==CNN_top_module_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CNN_top_module/ip/CNN_top_module_rst_ps7_0_50M_0/CNN_top_module_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CNN_top_module_rst_ps7_0_50M_0 || ORIG_REF_NAME==CNN_top_module_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CNN_top_module/ip/CNN_top_module_rst_ps7_0_50M_0/CNN_top_module_rst_ps7_0_50M_0_ooc.xdc

# XDC: bd/CNN_top_module/ip/CNN_top_module_auto_pc_0/CNN_top_module_auto_pc_0_ooc.xdc

# XDC: bd/CNN_top_module/CNN_top_module_ooc.xdc
